services:
  backend:
    build:
      context: ./back
    container_name: cafe-recommend-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./front
    container_name: cafe-recommend-frontend
    depends_on:
      - backend
    environment:
      API_URL: http://backend:8000/recommend
    ports:
      - "8501:8501"
